Update Total Nutrients class
gobble/edamam-ruby pull request #13
Opened 2017-05-24 16:24 UTC by andela-mpitan

Update the total nutrients class

Currently, we can only access the calorie of a count of a nutrient. We need to be able to access values for sodium, fat, and sugar.

This change addresses the need by:

* Adding helper methods to return sugar, fat and sodium, nutrient value objects
* Adding helper methods to return label, quantity, and unit of a nutrient value object

Resolves issue #12

2017-05-31 20:10 UTC, chriswoodford requested changes

2017-05-31 20:10 UTC, chriswoodford commented on lib/edamam-ruby/nutrient_value.rb
> +      @value = value
is `@value` being used as hash?

2017-05-31 20:10 UTC, chriswoodford commented on lib/edamam-ruby/nutrient_value.rb
> +  class NutrientValue
just `Nutrient` might be a better class name. `Value` isn't adding any clarity to the name. The edamam API returns `totalNutrients`, so it makes sense that the singular of that collection would be `Nutrient`

2017-06-19 17:39 UTC, andela-mpitan commented on lib/edamam-ruby/nutrient_value.rb
> +      @value = value
Yeah, @value is a hash

2017-06-19 17:57 UTC, chriswoodford requested changes

2017-06-19 17:57 UTC, chriswoodford commented on lib/edamam-ruby/nutrient_value.rb
> +      @value = value
you should never store a single instance variable in a class as a hash. use explicit properties for every value you need. you can use meta programming to reduce the burden of setting variables. or consider whether a gem like https://github.com/solnic/virtus is justified

2017-06-28 18:44 UTC, chriswoodford requested changes
just 2 small syntax things and this will be good to go

2017-06-28 18:44 UTC, chriswoodford commented on spec/food_database_spec.rb
> +        expect(result).to be_an_instance_of Edamam::Nutrient
`expect(result).to be_an_instance_of(Edamam::Nutrient)` 

don't forget to use the parentheses in your expectations. in general, the only time to not use the parenthesis is if it's a DSL and you do not capture any return value

2017-06-28 18:44 UTC, chriswoodford commented on spec/food_database_spec.rb
> +        expect(result).to be_an_instance_of Edamam::Nutrient
same for line 29

2017-06-28 19:44 UTC, chriswoodford approved these changes

2017-06-28 20:23 UTC, merged